Каркас кода и немного тестов для модуля логики DnD
cpp-park-vk-education/2022_2_Wild_Spirits pull request #4
Opened 2022-11-21 14:51 UTC by reddiridabl666

2022-11-30 01:32 UTC, DPeshkoff requested changes
Привет! Посмотрел 1-ю итерацию.

CI не проходит

Предварительная оценка: 3 / 10 (не проходит CI -50%, вопросы по коду -2)

2022-11-30 01:32 UTC, DPeshkoff commented on common/logic/include/activatable/Area.hpp
> +    static Area* create(int width = 0, int height = 0) {
int?

2022-11-30 01:32 UTC, DPeshkoff commented on common/logic/include/activatable/Damage.hpp
> +    size_t times_;
не соответствует UML

2022-11-30 01:32 UTC, DPeshkoff commented on common/logic/include/base/Dice.hpp
> +    static const inline std::set<uint8_t> valid_dice_ = {4, 6, 8, 10, 12, 20};
почему глобальная и статическая константа? чем обусловлено?

2022-11-30 01:32 UTC, DPeshkoff commented on common/logic/include/base/Resistible.hpp
> +    std::bitset<DamageTypes::maxNum()> vulnerabilities_;
Почему выбрал именно такой путь? 

2022-11-30 01:32 UTC, DPeshkoff commented on common/logic/include/base/StatBased.hpp
> +    using Stats = std::unordered_map<std::string, int>;
почему using в public

2022-11-30 01:32 UTC, DPeshkoff commented on common/logic/include/base/TurnBased.hpp
> +        if (turns_) --turns_;
{}

2022-11-30 01:32 UTC, DPeshkoff commented on common/logic/include/base/Utils.hpp
> +    int y = 0;
Почему int?

2022-11-30 01:32 UTC, DPeshkoff commented on common/logic/include/character/PlayerCharacter.hpp
> +        // class_list_.get(class_id)->getSkill(skill_id).use(target, dice ? 0 : dice->roll(20));
?

2022-11-30 01:32 UTC, DPeshkoff commented on common/logic/tests/logic-test.cpp
> +    ASSERT_FALSE(area.isInArea(Tile{5, 3}));
мне кажется, что лучше expect

2022-11-30 01:32 UTC, DPeshkoff commented on common/logic/tests/logic-test.cpp
> +class MockGameMap : public GameMap {
надо бы по разным файлам разнести

2022-12-06 09:43 UTC, reddiridabl666 commented on common/logic/include/base/StatBased.hpp
> +    using Stats = std::unordered_map<std::string, int>;
Я думаю, что это имеет смысл, т.к. например, объект типа Buff принимает StatBased::Stats в конструкторе. Конечно, он и обычный unordered_map примет, но мне кажется, лучше через using для более читабельного интерфейса

2022-12-12 17:53 UTC, DPeshkoff approved these changes
Привет! Посмотрел вторую итерацию.

Предварительная оценка: 10 / 10

2022-12-12 17:53 UTC, DPeshkoff commented on common/logic/include/activatable/Activatable.hpp
> +    CharacterInstance* actor_;
Почему выбрал именно обычный указатель, а не умный?

2022-12-12 17:53 UTC, DPeshkoff commented on common/logic/tests/src/effects-tests.cpp
> +    ASSERT_THROW(DealDamage(DamageType(0), -1, 2, std::make_unique<Dice>()), InvalidDice);
Кажется, лучше expect)

2023-01-05 00:30 UTC, merged